################################# Default configuration ###################
# provide your domain here
baseURL = "https://adversarial-driving.org/"
# theme
theme = "dot"
# site title
title = "Adversarial Driving"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#010126"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################

[[params.social]]
icon = "ti-home" # themify icon pack : https://themify.me/themify-icons
name = "Home"
link = "https://wuhanstudio.cc"

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
name = "Github"
link = "https://github.com/wuhanstudio"
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
name = "Linkedin"
link = "https://www.linkedin.com/in/han-wu-2b3773ab"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "Copyright © 2020 a Hugo theme by [Gethugothemes](https://gethugothemes.com/)"

# banner
[Languages.en.params.banner]
title = "Adversarial Driving"
subtitle = "Adversarial attacks against autonomous Driving"
bg_image = "images/banner.jpg"
placeholder = "Quick search"

# call to action
[Languages.en.params.cta]
enable = true
title = "Would like to know more about me?"
content = "I'm a Ph.D. Student at University of Exeter in the U.K. for Autonomous System Security. Prior research experience at RT-Thread, LAIX, Xilinx."
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "Hoempage"
link = "https://wuhanstudio.cc"


################## english navigation #################

[[Languages.en.menu.main]]
name = "simulation"
url = "simulation"
weight = 1

[[Languages.en.menu.main]]
name = "localization"
url = "localization"
weight = 2

[[Languages.en.menu.main]]
name = "perception"
url = "perception"
weight = 3

[[Languages.en.menu.main]]
name = "prediction"
url = "prediction"
weight = 4

[[Languages.en.menu.main]]
name = "planning"
url = "planning"
weight = 5

[[Languages.en.menu.main]]
name = "control"
url = "control"
weight = 6

# Dropdown menu
[[Languages.en.menu.main]]
weight = 7
name = "attacks"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "attacks"
  name = "Digital"
  url = "digital"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "attacks"
  name = "Physical"
  url = "physical"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "attacks"
  name = "Cloud API"
  url = "cloudapi"
  weight = 3

# Dropdown menu
[[Languages.en.menu.main]]
weight = 8
name = "defence"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "defence"
  name = "Quantization"
  url = "quantization"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "defence"
  name = "Interpretability"
  url = "interpretability"
  weight = 3

  [[Languages.en.menu.main]]
  parent = "defence"
  name = "Robustness"
  url = "robustness"
  weight = 3
